name: "Scripts Proxy Release"

permissions:
  contents: write
  packages: read

on:
  push:
    tags:
      - "SP/v*"

env:
  PROJECT_DIR: ScriptsProxy/
  VCXPROJ: ScriptsProxy/ScriptsProxy.vcxproj
  PUBLISH_DIR: x64/Release/

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
          vcpkgJsonGlob: '${{ env.PROJECT_DIR }}/vcpkg.json'
          vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'

      - name: Restore vcpkg packages
        run: vcpkg integrate install

      - name: Build
        run: msbuild /p:Configuration=Release /p:Platform=x64 ${{ env.VCXPROJ }}

      - name: Generate names by tag
        id: names
        shell: bash
        run: |
          {
            ref="${{ github.ref }}"
            ref=${ref//refs\/tags\//}

            release_name=${ref/SP\/v/Scripts Proxy (v. }
            echo "release_name=${release_name})" >> $GITHUB_OUTPUT

            archive_name=${ref/SP\/v/ScriptsProxy_v}
            archive_name=${archive_name// /_}
            echo "archive_name=${archive_name}.zip" >> $GITHUB_OUTPUT
          }

      - name: Zip the files
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: ${{ steps.names.outputs.archive_name }}
          directory: ${{ env.PUBLISH_DIR }}
          exclusions: "*.pdb *.exp *.lib"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.names.outputs.release_name }}
          body: ""
          artifacts: "${{ env.PUBLISH_DIR }}${{ steps.names.outputs.archive_name }}"
